
.. |xtc_tools_version| replace:: 15.3.1
.. |python_version|    replace:: 3.10
.. |cmake_version|     replace:: 3.21
.. _Python:            https://www.python.org/
.. _CMake:             https://cmake.org/


.. |vision board| replace:: xcore.ai Vision Development Kit
.. |vision board ref| replace:: `XK-EVK-XU316-AIV`

.. |explorer board| replace:: xcore.ai Explorer Development Kit
.. |explorer board ref| replace:: `XK-EVK-XU316`

.. _MIPI: https://www.mipi.org/specifications/csi-2
.. _XMOS: https://www.xmos.ai/
.. _XMOS I2C: https://github.com/xmos/fwk_io
.. _XMOS Programming Guide: https://www.xmos.ai/download/XMOS-Programming-Guide-(documentation)(E).pdf
.. _XMOS XC Programming Guide: https://www.xmos.ai/download/XMOS-Programming-Guide-(documentation)(E).pdf
.. _XMOS C Programming Guide: https://www.xmos.com/documentation/XM-014363-PC/html/prog-guide/quick-start/c-programming-guide/index.html

.. _IMX219: https://www.opensourceinstruments.com/Electronics/Data/IMX219PQ.pdf
.. _SW_TOOLS: https://www.xmos.ai/software-tools/
.. _xcore.ai: https://www.xmos.com/xcore-ai
.. _XMOS XS3 Architecture: https://www.xmos.com/download/The-XMOS-XS3-Architecture.pdf

.. |lib_camera| replace:: ``lib_camera``
.. |xcore-ai| replace:: ``xcore.ai``
