
.. _MIPI: https://www.mipi.org/specifications/csi-2
.. _XMOS: https://www.xmos.ai/
.. _XMOS I2C: https://www.xmos.ai/download/lib_i2c-%5Buserguide%5D(5.0.0rc3).pdf
.. _XMOS Programming Guide: https://www.xmos.ai/download/XMOS-Programming-Guide-(documentation)(E).pdf
.. _IMX219: https://www.opensourceinstruments.com/Electronics/Data/IMX219PQ.pdf
.. _SW_TOOLS: https://www.xmos.ai/software-tools/
.. _XSCOPE_FILEIO: https://github.com/xmos/xscope_fileio

.. |lib_camera| replace:: ``lib_camera``
.. |vision board| replace:: ``XCORE-VISION board``
.. |xcore-ai| replace:: ``xcore.ai``
